- name: add the brightbox repo
  apt_repository:
    repo: "{{brightbox}}"
    state: present

- name: install ruby
  apt:
    name: "{{item}}"
    state: latest
  with_items:
    - ruby2.3
    - ruby2.3-dev
    - ruby-switch

- name: set ruby to 2.3
  command: "ruby-switch --set ruby2.3"

- name: disable documentation
  lineinfile:
    create: yes
    state: present
    dest: /etc/gemrc
    insertafter: EOF
    line: "gem: --no-ri --no-rdoc"
    mode: 0644
    owner: root

- name: install gems
  gem:
    name: "{{item}}"
    state: latest
  with_items:
    - bundler
    - rake