- hosts: all
  remote_user: root
  tasks:
    - name: modify the root user
      user:
        name: root
        password: "$6$cMYmlKLXab8uhot9$W.5xRy6nfkMDW/X2yNljUW17rNXQIDFXmj0bmAmi6FbVzxOSrxcGxyMqWFTSblre3IGXV/q3VvWBVUDN44Pgc1"
        shell: /bin/bash
        groups: root
        home: /root
        state: present

    - name: create user malakai
      user:
        name: malakai
        password: "$6$d9txRo1N$0ORHJVtdWnYxPniLVUn3kQiRhSQPYwQCrU49AhQJcNJ7mafZrTbXuzdmh/nCXEIgwzF/WwJXUnenRx73QBGuR."
        group: users
        home: /home/malakai
        shell: /bin/bash
        uid: 1337

    - name: Add public key for malakai
      authorized_key:
        user: malakai
        key: "{{ item }}"
        state: present
      with_items: user.me.public_keys

    - name: add malakai to sudoers
      lineinfile:
        dest: /etc/sudoers
        state: present
        insertafter: EOF
        line: "malakai ALL=(ALL) NOPASSWD: ALL"
        validate: "visudo -cf %s"
