---
- name: Load application specifics.
  become: no
  hosts: all
  vars_files: 
    - "{{ config_file }}"
  roles:
    - role: setup

- name: Prepare host that will run the app.
  hosts: app
  become: yes
  become_method: sudo
  roles:
    - role: user 
    - role: db-user 
    - role: target
    - role: puma-svc 
    - role: rbenv-ver 

- name: Prepare MySQL host.
  hosts: db
  become: yes
  become_method: sudo
  roles:
    - role: db

- name: Prepare Solr host.
  hosts: solr
  become: yes
  become_method: sudo
  roles:
    - role: solr-core
    
- name: Prepare Apache host.
  hosts: web
  become: yes
  become_method: sudo
  roles:
    - role: apache-config

