---
- name: provision a vagrant box to test roles and playbooks.
  hosts: vagrant
  #user: vagrant
  remote_user: vagrant
  #gather_facts: true
  vars:
    #leave blank; don't need ssh keys for vagrant instance.
    - keys_to_add:
    - app_name: demo
    - app_stage: staging
    - app_repo:  https://github.com/mlibrary/umrdr
    - user_gid:  123456
    - user_uid:  987654
    - deploy_root: /hydra-dev
    - deploy_users:
      - vagrant
      - grosscol
      - otherguy
    - dependency_mysql: no
    - dependency_solr: no
    - dependency_resque: no
    - ruby_version: 2.3.0
    - rbenv_root: /l/local/rbenv
    - solr_core: /hydra-dev/solr/cores/umrdr-staging
    - solr_home: /var/lib/solr/home
  roles:
    - { role: vmock, tags: ["testing", "vagrant"] }
    - { role: zzet.rbenv, tags: ["testing", "vagrant"] }
    - { role: setup }
    - { role: user }
    - { role: puma-svc }
    - { role: rbenv-ver }
    - { role: solr-core }
