---
- name: Minimal provisioning of Vagrant Box as testing target.
  hosts: vagrant
  remote_user: vagrant
  roles:
    - { role: vmock, tags: ["testing", "vagrant"] }
    - { role: zzet.rbenv, tags: ["testing", "vagrant"] }

