---
- name: Load application specifics.
  hosts: all
  vars_files: 
    - "{{ config_file }}"
  roles:
    - { role: setup }

- name: Prepare host that will run the app.
  hosts: app
  roles:
    - role: user 
    - role: db-user 
      become: yes
    - role: puma-svc 
    - role: rbenv-ver 

- name: Prepare MySQL host.
  hosts: db
  roles:
    - { role: db }

- name: Prepare Solr host.
  hosts: solr
  roles:
    - { role: solr-core }

- name: Prepare Apache host.
  hosts: web
  roles:
    - { role: apache-config }

