---
- name: Run testing script on vagrant box
  hosts: test
  remote_user: vagrant
  become: yes
  vars_files: 
    - "{{ config_file }}"
  roles:
    - role: vmock-test
      tags: ["testing", "vagrant"]

