- hosts: production
  become: yes
  remote_user: malakai
  vars_files:
    - vars/mysql.yml
  vars:
  pre_tasks:
    - name: generate a password for root
      shell: openssl rand -base64 32 | tr -dc A-Za-z0-9
      register: password_for_mysql_root
  roles:
    - hostname
    - kamaln7.swapfile # vars/swap.yml
    - common-packages
    - git
    - mail
    - ntp
    - geerlingguy.mysql # var/mysql.yml
    - nginx
    - ruby-prod
    - firewall
