- hosts: production
  become: yes
  remote_user: malakai
  vars:
  roles:
#    - hostname
#    - common-packages
#    - git
#    - mail
#    - ntp
#    - mysql
#    - nginx
#    - ruby-prod
    - firewall
