- hosts: {{hosts}}
#  become: yes
  vars:
  roles:
    - ruby-prod
    - role: rails-prod
      name: tephue
      url: tephue.com
      basepath: /var
      num_queues: 0
      group:
        gid: 200
        name: tephue
      user:
        uid: 1400
        name: tephue
        public_keys: "{{user.me.public_keys}}"
