---
- name: provision a vagrant box to test roles and playbooks.
  hosts: vagrant
  #user: vagrant
  remote_user: vagrant
  #gather_facts: true
  vars:
    #leave blank; don't need ssh keys for vagrant instance.
    - keys_to_add:
    - app_name: demo-app
    - user_gid:  123456
    - user_uid:  987654
    - deploy_users:
      - vagrant
      - grosscol
      - bhockey
    - dependency_mysql: no
    - dependency_solr: no
    - dependency_resque: no
  roles:
    - { role: setup }
    - { role: user }
