- hosts: all
  become: true
  vars:
    email_domain: bryan.hockey

  tasks:
    - name: modify the root user
      user:
        name: root
        password: "{% verbatim %}{{ root_password }}{% endverbatim %}"
        shell: /bin/bash
        groups: root
        home: /root
        state: present

    - name: create user malakai
      user:
        name: malakai
        password: "{% verbatim %}{{ malakai_password }}{% endverbatim %}"
        group: users
        home: /home/malakai
        shell: /bin/bash
        uid: 1337

    - name: Add public key for malakai
      authorized_key:
        user: malakai
        key: "{% verbatim %}{{ public_key_malakai }}{% endverbatim %}"
        state: present

    - name: add malakai to sudoers
      lineinfile:
        dest: /etc/sudoers
        state: present
        insertafter: EOF
        line: "malakai ALL=(ALL) NOPASSWD: ALL"
        validate: "visudo -cf %s"