---
- name: Create the app's system group
  group:
    gid: "{{user_gid}}"
    name: "{{user_group}}"
    state: present
    system: no

- name: Create the app's system user
  user:
    uid: "{{user_uid}}"
    name: "{{user_name}}"
    group: "{{user_group}}"
    comment: "{{user_comment}}"
    createhome: yes
    home: "/var/{{user_name}}"
    shell: /bin/bash
    system: yes

- name: Add deployment users to app group
  user:
    name: "{{item}}"
    append: yes
    groups: "{{user_group}}"
  with_items: "{{ user_deploy_users }}"


