- name: Create the database
  mysql_db:
    name: "{{name}}"
    state: present

- include: my.cnf.yml
  vars:
    user: "{{user.name}}"
    password: "{{user.db_password}}"
    dest: "/home/{{user.name}}/.my.cnf"

- name: Create the app DB user
  mysql_user:
    name: "{{user.name}}"
    password: "{{user.db_password}}"
    host: localhost
    priv: "{{name}}.*:DELETE,EXECUTE,INSERT,LOCK_TABLES,SELECT,UPDATE"

- include: my.cnf.yml
  vars:
    user: "{{deploy_user.name}}"
    password: "{{deploy_user.db_password}}"
    dest: "/home/{{deploy_user.name}}/.my.cnf"

- name: Create the app DB deploy user
  mysql_user:
    name: "{{deploy_user.name}}"
    password: "{{deploy_user.db_password}}"
    host: localhost
    priv: "{{name}}.*:ALL"