- include: pre.yml
- include: user.yml
- include: db.yml

- name: Create the project directory
  file:
    state: directory
    path: "{{app_path}}"
    owner: "{{user.name}}"
    group: "{{group.name}}"
    mode: 0775

- name: Create shared files directory
  file:
    state: directory
    path: "{{app_path}}/shared/config"
    owner: "{{user.name}}deploy"
    group: "{{group.name}}"

- name: Install the shared database.yml
  template:
    src: database.yml.j2
    dest: "{{app_path}}/shared/config/database.yml"
    force: yes
    owner: "{{user.name}}deploy"
    group: "{{group.name}}"
    mode: u=rw,g=r,o-rwx

- include: nginx.yml
- include: systemd.yml

