- name: Generate DB password for app user
  shell: openssl rand -base64 32 | tr -dc A-Za-z0-9
  register: user_db_password

- name: Generate DB password for app deploy user
  shell: openssl rand -base64 32 | tr -dc A-Za-z0-9
  register: deploy_user_db_password

- set_fact:
    app_path: "{{ basepath + '/' + name }}"
    deploy_user:
      name: "{{ user.name + 'deploy' }}"
      db_password: "{{ deploy_user_db_password }}"
    user:
      db_password: "{{ user_db_password }}"

