---

- name: Install primary systemd service file (no queues)
  template:
    src: app.service.j2
    dest: "/etc/systemd/system/{{name}}.service"
    force: yes
    owner: root
    group: root
    mode: u=rwx,g=rx,o=rx
  when: num_queues == 0

- name: Install primary systemd service file (with queues)
  template:
      src: app_with_queues.service.j2
      dest: "/etc/systemd/system/{{name}}.service"
      force: yes
      owner: root
      group: root
      mode: u=rwx,g=rx,o=rx
    when: num_queues > 0

- name: Install systemd queues target
  template:
      src: app-queues.target.j2
      dest: "/etc/systemd/system/{{name}}-queues.target"
      force: yes
      owner: root
      group: root
      mode: u=rwx,g=rx,o=rx
    when: num_queues > 0

- name: Install systemd queues service
  template:
      src: app-queue@.service.j2
      dest: "/etc/systemd/system/{{name}}-queues@.service"
      force: yes
      owner: root
      group: root
      mode: u=rwx,g=rx,o=rx
    when: num_queues > 0
