---
- name: Check required varaibles
  assert: { that: "item is defined" }
  with_items:
    - puma_svc_rbenv_root
    - puma_svc_deploy_dir
    - puma_svc_app_name

- name: Install puma service
  template:
    src:   app-puma@.service
    dest:  /etc/systemd/system/app-puma@.service
    owner: root
    group: root
    mode:  u=rw,g=r,o=r

- name: Create puma service config directory
  file:
    path:  /etc/systemd/system/app-puma@{{puma_svc_app_name}}.service.d
    state: directory

- name: Install puma service drop-in config
  template:
    src:   app-puma@.service.d/drop-in.conf.j2 
    dest:  /etc/systemd/system/app-puma@{{puma_svc_app_name}}.service.d/drop-in.conf
    owner: root
    group: root
    mode:  u=rwx,g=rx,o=rx

- include: resque.yml
  when:  puma_svc_resque_dependency

- name: Reload systemd service files
  shell: systemctl daemon-reload

- name: Install sudoers.d template for app-puma service mgmt
  template:
    src:   sudoers.d.j2
    dest: /etc/sudoers.d/app-puma-{{puma_svc_app_name}}
    owner: root
    group: root
    mode: u=r,g=r
