---
- name: Install resque-pool service
  become: yes
  template:
    src:   resque-pool@.service.j2 
    dest:  /etc/systemd/system/resque-pool@{{puma_svc_app_name}}-{{puma_svc_app_stage}}.service
    owner: root
    group: root
    mode:  u=rwx,g=rx,o=rx

- name: Create resque-pool service config directory
  become: yes
  file:
    path:  /etc/systemd/system/resque-pool@{{puma_svc_app_name}}-{{puma_svc_app_stage}}.service.d
    state: directory

- name: Install resque-pool service drop-in config
  become: yes
  template:
    src:   resque-pool@.service.d/drop-in.conf.j2 
    dest:  /etc/systemd/system/resque-pool@{{puma_svc_app_name}}-{{puma_svc_app_stage}}.service.d/{{puma_svc_app_stage}}.conf
    owner: root
    group: root
    mode:  u=rwx,g=rx,o=rx
