- name: install ufw
  apt:
    name: ufw
    state: latest

- name: default deny
  ufw:
    state: disabled
    policy: deny
    logging: "off"

- name: allow outgoing
  ufw:
    state: disabled
    rule: allow
    direction: out

- name: allow ssh
  ufw:
    state: disabled
    rule: allow
    port: 22
    proto: tcp

- name: reload ufw
  ufw:
    state: enabled

