- name: generate a password for root
  shell: "cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w 32 | head -n 1"
  register: mysql_root_password

- name: Install mysql
  apt:
    pkg: "{{item}}"
    state: installed
  with_items:
    - mysql-client
    - mysql-server
    - libmysqlclient-dev

- name: start mysqld service
  service:
    name: mysql
    state: restarted

- name: run mysql_install_db
  command: mysql_install_db

- name: create /root/.my.cnf
  template:
    src: my.cnf.j2
    dest: /root/.my.cnf
    mode: 600
    owner: root
    group: root

- name: secure mysql installation
  shell: "{{item}}"
  with_items:
    - mysql -u root -p{{mysql_root_password}} -e "UPDATE mysql.user SET Password=PASSWORD('{{mysql_root_password}}') WHERE User='root'"
    - mysql -u root -p{{mysql_root_password}} -e "DELETE FROM mysql.user WHERE User='root' AND Host NOT IN ('localhost', '127.0.0.1', '::1')"
    - mysql -u root -p{{mysql_root_password}} -e "DELETE FROM mysql.user WHERE User=''"
    - mysql -u root -p{{mysql_root_password}} -e "DELETE FROM mysql.db WHERE Db='test' OR Db='test\_%'"
    - mysql -u root -p{{mysql_root_password}} -e "FLUSH PRIVILEGES"

