- name: generate a password for root
  shell: openssl rand -base64 32 | tr -dc A-Za-z0-9
  register: mysql_root_password

- name: Install mysql
  apt:
    pkg: "{{item}}"
    state: installed
  with_items:
    - mysql-client
    - mysql-server
    - libmysqlclient-dev

- name: start mysqld service
  service:
    name: mysql
    state: restarted

- name: run mysql_install_db
  command: mysql_install_db

- name: create /root/.my.cnf
  template:
    src: my.cnf.j2
    dest: /root/.my.cnf
    mode: 600
    owner: root
    group: root

- name: secure mysql installation
  shell:
    free_form: "{{item}}"
    executable: /bin/bash
  with_items:
    - mysql -u root -p{{mysql_root_password.stdout}} -e "UPDATE mysql.user SET Password=PASSWORD('{{mysql_root_password.stdout}}') WHERE User='root'"
    - mysql -u root -p{{mysql_root_password.stdout}} -e "DELETE FROM mysql.user WHERE User='root' AND Host NOT IN ('localhost', '127.0.0.1', '::1')"
    - mysql -u root -p{{mysql_root_password.stdout}} -e "DELETE FROM mysql.user WHERE User=''"
    - mysql -u root -p{{mysql_root_password.stdout}} -e "DELETE FROM mysql.db WHERE Db='test' OR Db='test\_%'"
    - mysql -u root -p{{mysql_root_password.stdout}} -e "FLUSH PRIVILEGES"

