---

- name: Install apache2 package
  package:
    name: apache2
    state: present

- name: Copy over mod_cosign 
  copy:
    src:   "lib/mod_cosign.so"
    dest:  "/usr/lib/apache2/modules/mod_cosign.so"
    owner: root
    group: root

- name: Add cosign to mods avaialble
  copy: 
    content: "LoadModule cosign_module      /usr/lib/apache2/modules/mod_cosign.so"
    dest: "/etc/apache2/mods-available/cosign.load"
    owner: root
    group: root
    mode: u=rw,g=r,o=r

- name: Enable required apache mods
  apache2_module:
    name: "{{ item }}"
    state: present
  with_items:
    - macro
    - rewrite
    - headers
    - proxy
    - cosign
    - ssl
    - proxy_http

- name: Copy common macros stubs
  template:
    src:   common_macros.conf.j2 
    dest:  /etc/apache2/conf-available/common_macros.conf
    owner: root
    group: root
    mode:  u=rwx,g=rx,o=rx

- name: Enable common macros
  command: a2enconf common_macros
  args:
    creates: /etc/apache2/conf-enabled/common_macros.conf

- name: generate self-signed ssl certificates
  command: openssl req -new -nodes -x509 -subj "/C=US/ST=Michigan/L=Ann Arbor/O=Library IT/CN={{ apache_domain }}" -keyout  /etc/ssl/private/{{ apache_ssl_key }} -out /etc/ssl/certs/{{ apache_ssl_crt }} -days 365
  args:
    creates: /etc/ssl/certs/{{ apache_ssl_crt }}

- name: restart apache2
  service: 
    name: apache2
    state: restarted

- name: Add front end host to hosts file
  lineinfile:
    dest: /etc/hosts
    state: present
    insertafter: EOF
    line: "127.0.0.1 {{ apache_domain }}"


