---

- name: Create dirs to mock the deploy root mount points
  file:
    path:  /hydra
    state: directory
    mode: u=rwx,g=rwx,o=rx

- name: Create dirs to mock the deploy root mount points
  file:
    path:  /hydra-dev
    state: directory
    mode: u=rwx,g=rwx,o=rx

- name: Create dir to mock solr core locations
  file:
    path:  /hydra-dev/solr/cores/
    state: directory
    mode:  u=rwx,g=rwx,o=rx

- name: Create dir to mock local filesystem idiosyncracy
  file:
    path:  /l/local
    state: directory
    mode: u=rwx,g=rwx,o=rx

- name: Create dir to mock solr directory structure
  file:
    path:  /var/lib/solr6/home
    state: directory
    mode:  u=rwx,g=rwx,o=rx

- name: Create symlink to mock solr directory structure
  file:
    path:  /var/lib/solr
    src:   /var/lib/solr6
    state: link
    mode:  u=rwx,g=rwx,o=rx

