---

- name: Update package manager cache
  package:
    update_cache: yes

- include: dirs.yml
- include: solr.yml
- include: apache.yml
- include: mysql.yml

- name: Create db deploy_users
  mysql_user:
    name: "{{item}}"
    password: x
    host: "%"
  with_items: "{{vmock_deploy_users}}"
