---
- name: Create dirs to mock the deploy root mount points
  become: yes
  file:
    path:  /hydra
    state: directory
    mode: u=rwx,g=rwx,o=rwx

- name: Create dirs to mock the deploy root mount points
  become: yes
  file:
    path:  /hydra-dev
    state: directory
    mode: u=rwx,g=rwx,o=rwx
