---

- include: dirs.yml
- include: solr.yml

- name: Update package manager cache
  package:
    update_cache: yes

- name: Install mysql server
  package:
    name: mysql-server
    state: present

- name: Install mysql client
  package:
    name: mysql-client
    state: present

- name: Install python-mysql package
  package:
    name: python-mysqldb
    state: present

- name: Create db deploy_users
  mysql_user:
    name: "{{item}}"
    password: x
    host: "%"
  with_items: "{{vmock_deploy_users}}"

