---

- include: dirs.yml
- include: solr.yml

- name: Install mysql server
  become: yes
  package:
    name: mysql-server
    state: present

- name: Install mysql client
  become: yes
  package:
    name: mysql-client
    state: present

