---

- name: check rbenv ruby {{rbenv_ver_ruby_version}}
  shell: bash -c "RBENV_ROOT={{rbenv_ver_rbenv_root}} {{rbenv_ver_rbenv_root}}/bin/rbenv versions | grep {{rbenv_ver_ruby_version}}"
  register: ruby_ver_installed
  ignore_errors: yes
  tags: 
    - ruby

- fail:
    msg: Required ruby version {{rbenv_ver_ruby_version}} not available in rbenv.
  when: ruby_ver_installed|failed
  tags:
    - ruby
