- name: Create the database
  become: yes
  mysql_db:
    encoding: utf8
    name: "{{db_name}}"
    state: present

- name: Generate DB password for app user
  shell: openssl rand -base64 32 | tr -dc A-Za-z0-9
  register: db_user_password

- include: my.cnf.yml
  vars:
    cnf_app_user: "{{db_app_user}}"
    cnf_db_user:  "{{db_user_name}}"
    cnf_db_password: "{{db_user_password}}"
    cnf_dest: "{{db_user_home}}/.my.cnf"
    
- name: Create the app DB user
  become: yes
  mysql_user:
    name: "{{db_user_name}}"
    password: "{{db_user_password}}"
    host: localhost

- name: Grant table privs to the app DB user
  become: yes
  mysql_user:
    name: "{{db_user_name}}"
    password: "{{db_user_password}}"
    append_privs: yes
    host: localhost
    priv: "{{db_name}}.*:DELETE,EXECUTE,INSERT,SELECT,UPDATE"
    
- name: Grant privileges to deploy users
  become: yes
  mysql_user:
    name: "{{item}}"
    append_privs: yes
    priv: "{{db_name}}.*:ALL"
  with_items: "{{db_deploy_users}}"

    
