---

- name: Create conf directory
  file:
    path:  "{{solr_core_path}}/conf"
    state: directory
    owner: solr
    group: solr
    mode: 2775

- name: Configure temporary local directory
  set_fact:
    solr_core_tmp_path: /tmp/ansible-predeploy/{{9999|random(start=1000)}}/{{solr_core_name}}/solr/config
      
- name: Check out solr config locally
  become: no
  delegate_to: localhost
  subversion:
    repo: "{{solr_core_repo}}/trunk/solr/config"
    dest: "{{solr_core_tmp_path}}"
    switch: no
    force: yes
    
- name: Populate core conf 
  copy:
    src:   "{{solr_core_tmp_path}}"
    dest:  "{{solr_core_path}}/conf"
    owner: solr
    group: solr
  become: yes

- name: Create core.properties
  copy:
    content: "name={{solr_core_name}}"
    dest:    "{{solr_core_path}}/core.properties"
    owner:   solr
    group:   solr

- name: Create link to core directory in solr home
  file:
    path:  "{{solr_core_home}}/{{ solr_core_name }}"
    src:   "{{solr_core_path}}"
    state: link
