- become: true
  vars:

  tasks:
    - name: create app group
      group:
        gid: "{{app.group.gid}}"
        name: "{{app.group.name}}"
        state: present

    - name: create the app user
      user:
        name: "{{app.user}}"
        group: "{{app.group.name}}"
        comment: "{{app.name}} user"
        createhome: yes
        shell: /bin/bash
        system: yes

    - name: create the deploy user
      user:
        name: "{{app.user}}deploy"
        group: "{{app.group.name}}"
        comment: "{{app.name}} deploy user"
        createhome: yes
        shell: /bin/bash
        system: yes
