- become: true
  tasks:
    - name: install update-manager-core
      apt:
        pkg: update-manager-core
        state: latest

    - name: run the release upgrade
      command: do-release-upgrade

    - name: reboot the server
      command: shutdown -r now "Ansible updates triggered"
      async: 0
      poll: 0
      ignore_errors: true

    - name: wait for the server to come back
      local_action:
        wait_for:
          host: "{{ invenory_hostname }}"
          state: started
          port: 22
          delay: 30
          connect_timeout: 30
          timeout: 300
      sudo: false