---
    
- name: Create the user's my.cnf
  template:
    src:   my.cnf.j2
    dest:  "{{db_user_app_user_home}}/.my.cnf"
    force: yes
    owner: "{{db_user_app_user}}"
    group: "{{db_user_app_group}}"
    mode:  u=rw,g=r

