---
- name: Create app group
# become: yes
  group: name={{ app_name }}
         gid={{ app_gid }}
         system=no
         state=present

- name: Create app user
# become: yes
  user: name={{ app_name }}
        uid={{ app_uid }}
        shell=/bin/bash
        home=/var/{{ app_name }}
        group={{ app_name }}
        state=present

- name: Add deployment users to app group
  user: name={{ item }}
        append=yes
        groups={{ app_name }}
  with_items: "{{ deploy_users }}"




